services:
  # FastAPI приложение
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://investv2:password@postgres:5432/investv2
      - REDIS_URL=redis://redis:6379/0
      - DEBUG=true
    depends_on:
      - postgres
      - redis
    networks:
      - investv2-network

  # PostgreSQL база данных
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: investv2
      POSTGRES_PASSWORD: password
      POSTGRES_DB: investv2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - investv2-network

  # Redis для кеширования
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - investv2-network

  # pgAdmin для управления БД (опционально)
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@investv2.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - investv2-network

volumes:
  postgres_data:
  redis_data:

networks:
  investv2-network:
    driver: bridge
