services:
  # FastAPI приложение
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://gen_user:%1umkt{~ZFy#m4@192.168.0.4:5432/investv2
      - REDIS_URL=redis://redis:6379/0
      - DEBUG=false
      - SECRET_KEY=${SECRET_KEY:-your-very-secret-key-change-in-production}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-["*"]}
    depends_on:
      - redis
    networks:
      - investv2-network
    restart: unless-stopped

  # Redis для кеширования
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - investv2-network
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  redis_data:

networks:
  investv2-network:
    driver: bridge
